services:
  jumpserver:
    restart: always
    image: whatwewant/jumpserver:${SERVICE_JUMPSERVER_IMAGE_VERSION}
    ports:
      - ${SERVICE_JUMPSERVER_HTTP_PORT}:80
      - ${SERVICE_JUMPSERVER_SSH_PORT}:2222
    environment:
      SECRET_KEY: $SERVICE_JUMPSERVER_SECRET_KEY
      BOOTSTRAP_TOKEN: $SERVICE_JUMPSERVER_BOOTSTRAP_TOKEN
      DEBUG: $SERVICE_JUMPSERVER_DEBUG
      LOG_LEVEL: $SERVICE_JUMPSERVER_LOG_LEVEL
      DB_HOST: $SERVICE_JUMPSERVER_MYSQL_HOST
      DB_PORT: $SERVICE_JUMPSERVER_MYSQL_PORT
      DB_USER: $SERVICE_JUMPSERVER_MYSQL_USER
      DB_PASSWORD: $SERVICE_JUMPSERVER_MYSQL_PASS
      DB_NAME: $SERVICE_JUMPSERVER_MYSQL_DB_NAME
      REDIS_HOST: $SERVICE_JUMPSERVER_REDIS_HOST
      REDIS_PORT: $SERVICE_JUMPSERVER_REDIS_PORT
      REDIS_PASSWORD: $SERVICE_JUMPSERVER_REDIS_PASSWORD
      # @TODO
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      
networks:
  default:
    external: true
    name: compose-ingress
